// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conn.proto

package connect

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NullResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullResp) Reset()         { *m = NullResp{} }
func (m *NullResp) String() string { return proto.CompactTextString(m) }
func (*NullResp) ProtoMessage()    {}
func (*NullResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{0}
}

func (m *NullResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullResp.Unmarshal(m, b)
}
func (m *NullResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullResp.Marshal(b, m, deterministic)
}
func (m *NullResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullResp.Merge(m, src)
}
func (m *NullResp) XXX_Size() int {
	return xxx_messageInfo_NullResp.Size(m)
}
func (m *NullResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NullResp.DiscardUnknown(m)
}

var xxx_messageInfo_NullResp proto.InternalMessageInfo

type NullReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullReq) Reset()         { *m = NullReq{} }
func (m *NullReq) String() string { return proto.CompactTextString(m) }
func (*NullReq) ProtoMessage()    {}
func (*NullReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1}
}

func (m *NullReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullReq.Unmarshal(m, b)
}
func (m *NullReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullReq.Marshal(b, m, deterministic)
}
func (m *NullReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullReq.Merge(m, src)
}
func (m *NullReq) XXX_Size() int {
	return xxx_messageInfo_NullReq.Size(m)
}
func (m *NullReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NullReq.DiscardUnknown(m)
}

var xxx_messageInfo_NullReq proto.InternalMessageInfo

type GetsQueryItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	Handle               string   `protobuf:"bytes,3,opt,name=Handle,proto3" json:"Handle,omitempty"`
	NextHandle           string   `protobuf:"bytes,4,opt,name=NextHandle,proto3" json:"NextHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetsQueryItem) Reset()         { *m = GetsQueryItem{} }
func (m *GetsQueryItem) String() string { return proto.CompactTextString(m) }
func (*GetsQueryItem) ProtoMessage()    {}
func (*GetsQueryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2}
}

func (m *GetsQueryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsQueryItem.Unmarshal(m, b)
}
func (m *GetsQueryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsQueryItem.Marshal(b, m, deterministic)
}
func (m *GetsQueryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsQueryItem.Merge(m, src)
}
func (m *GetsQueryItem) XXX_Size() int {
	return xxx_messageInfo_GetsQueryItem.Size(m)
}
func (m *GetsQueryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsQueryItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetsQueryItem proto.InternalMessageInfo

func (m *GetsQueryItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetsQueryItem) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func (m *GetsQueryItem) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *GetsQueryItem) GetNextHandle() string {
	if m != nil {
		return m.NextHandle
	}
	return ""
}

type GetsReq struct {
	Query                []*GetsQueryItem `protobuf:"bytes,1,rep,name=Query,proto3" json:"Query,omitempty"`
	OrderBy              string           `protobuf:"bytes,2,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Sort                 string           `protobuf:"bytes,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Current              int64            `protobuf:"varint,4,opt,name=Current,proto3" json:"Current,omitempty"`
	PageSize             int64            `protobuf:"varint,5,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetsReq) Reset()         { *m = GetsReq{} }
func (m *GetsReq) String() string { return proto.CompactTextString(m) }
func (*GetsReq) ProtoMessage()    {}
func (*GetsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3}
}

func (m *GetsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetsReq.Unmarshal(m, b)
}
func (m *GetsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetsReq.Marshal(b, m, deterministic)
}
func (m *GetsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetsReq.Merge(m, src)
}
func (m *GetsReq) XXX_Size() int {
	return xxx_messageInfo_GetsReq.Size(m)
}
func (m *GetsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetsReq proto.InternalMessageInfo

func (m *GetsReq) GetQuery() []*GetsQueryItem {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetsReq) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *GetsReq) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *GetsReq) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *GetsReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SendOneMsgReq struct {
	SenderType           string   `protobuf:"bytes,1,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	SenderId             string   `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderDeviceId       string   `protobuf:"bytes,3,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	ReceiverId           string   `protobuf:"bytes,4,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiverDeviceId     string   `protobuf:"bytes,5,opt,name=receiver_device_id,json=receiverDeviceId,proto3" json:"receiver_device_id,omitempty"`
	ParentId             string   `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SendTime             string   `protobuf:"bytes,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	MsgType              string   `protobuf:"bytes,8,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgContent           string   `protobuf:"bytes,9,opt,name=msg_content,json=msgContent,proto3" json:"msg_content,omitempty"`
	IsLocal              bool     `protobuf:"varint,10,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOneMsgReq) Reset()         { *m = SendOneMsgReq{} }
func (m *SendOneMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendOneMsgReq) ProtoMessage()    {}
func (*SendOneMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4}
}

func (m *SendOneMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOneMsgReq.Unmarshal(m, b)
}
func (m *SendOneMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOneMsgReq.Marshal(b, m, deterministic)
}
func (m *SendOneMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOneMsgReq.Merge(m, src)
}
func (m *SendOneMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendOneMsgReq.Size(m)
}
func (m *SendOneMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOneMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendOneMsgReq proto.InternalMessageInfo

func (m *SendOneMsgReq) GetSenderType() string {
	if m != nil {
		return m.SenderType
	}
	return ""
}

func (m *SendOneMsgReq) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *SendOneMsgReq) GetSenderDeviceId() string {
	if m != nil {
		return m.SenderDeviceId
	}
	return ""
}

func (m *SendOneMsgReq) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *SendOneMsgReq) GetReceiverDeviceId() string {
	if m != nil {
		return m.ReceiverDeviceId
	}
	return ""
}

func (m *SendOneMsgReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SendOneMsgReq) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *SendOneMsgReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *SendOneMsgReq) GetMsgContent() string {
	if m != nil {
		return m.MsgContent
	}
	return ""
}

func (m *SendOneMsgReq) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

type At struct {
	IsAtAll              bool     `protobuf:"varint,1,opt,name=is_atAll,json=isAtAll,proto3" json:"is_atAll,omitempty"`
	AtUserIds            []string `protobuf:"bytes,2,rep,name=at_userIds,json=atUserIds,proto3" json:"at_userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *At) Reset()         { *m = At{} }
func (m *At) String() string { return proto.CompactTextString(m) }
func (*At) ProtoMessage()    {}
func (*At) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5}
}

func (m *At) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_At.Unmarshal(m, b)
}
func (m *At) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_At.Marshal(b, m, deterministic)
}
func (m *At) XXX_Merge(src proto.Message) {
	xxx_messageInfo_At.Merge(m, src)
}
func (m *At) XXX_Size() int {
	return xxx_messageInfo_At.Size(m)
}
func (m *At) XXX_DiscardUnknown() {
	xxx_messageInfo_At.DiscardUnknown(m)
}

var xxx_messageInfo_At proto.InternalMessageInfo

func (m *At) GetIsAtAll() bool {
	if m != nil {
		return m.IsAtAll
	}
	return false
}

func (m *At) GetAtUserIds() []string {
	if m != nil {
		return m.AtUserIds
	}
	return nil
}

type SendManyMsgReq struct {
	SenderType           string   `protobuf:"bytes,1,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	SenderId             string   `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderDeviceId       string   `protobuf:"bytes,3,opt,name=sender_device_id,json=senderDeviceId,proto3" json:"sender_device_id,omitempty"`
	ReceiverId           []string `protobuf:"bytes,4,rep,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiverDeviceId     string   `protobuf:"bytes,5,opt,name=receiver_device_id,json=receiverDeviceId,proto3" json:"receiver_device_id,omitempty"`
	ParentId             string   `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SendTime             string   `protobuf:"bytes,7,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	At                   *At      `protobuf:"bytes,8,opt,name=at,proto3" json:"at,omitempty"`
	MsgType              string   `protobuf:"bytes,9,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgContent           string   `protobuf:"bytes,10,opt,name=msg_content,json=msgContent,proto3" json:"msg_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendManyMsgReq) Reset()         { *m = SendManyMsgReq{} }
func (m *SendManyMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendManyMsgReq) ProtoMessage()    {}
func (*SendManyMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{6}
}

func (m *SendManyMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendManyMsgReq.Unmarshal(m, b)
}
func (m *SendManyMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendManyMsgReq.Marshal(b, m, deterministic)
}
func (m *SendManyMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendManyMsgReq.Merge(m, src)
}
func (m *SendManyMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendManyMsgReq.Size(m)
}
func (m *SendManyMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendManyMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendManyMsgReq proto.InternalMessageInfo

func (m *SendManyMsgReq) GetSenderType() string {
	if m != nil {
		return m.SenderType
	}
	return ""
}

func (m *SendManyMsgReq) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *SendManyMsgReq) GetSenderDeviceId() string {
	if m != nil {
		return m.SenderDeviceId
	}
	return ""
}

func (m *SendManyMsgReq) GetReceiverId() []string {
	if m != nil {
		return m.ReceiverId
	}
	return nil
}

func (m *SendManyMsgReq) GetReceiverDeviceId() string {
	if m != nil {
		return m.ReceiverDeviceId
	}
	return ""
}

func (m *SendManyMsgReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SendManyMsgReq) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *SendManyMsgReq) GetAt() *At {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *SendManyMsgReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *SendManyMsgReq) GetMsgContent() string {
	if m != nil {
		return m.MsgContent
	}
	return ""
}

type GetConnectInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectInfoReq) Reset()         { *m = GetConnectInfoReq{} }
func (m *GetConnectInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetConnectInfoReq) ProtoMessage()    {}
func (*GetConnectInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{7}
}

func (m *GetConnectInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectInfoReq.Unmarshal(m, b)
}
func (m *GetConnectInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectInfoReq.Marshal(b, m, deterministic)
}
func (m *GetConnectInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectInfoReq.Merge(m, src)
}
func (m *GetConnectInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetConnectInfoReq.Size(m)
}
func (m *GetConnectInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectInfoReq proto.InternalMessageInfo

func (m *GetConnectInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetConnectInfoReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ConnectInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServerIp             string   `protobuf:"bytes,3,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`
	ConnectIp            string   `protobuf:"bytes,4,opt,name=connect_ip,json=connectIp,proto3" json:"connect_ip,omitempty"`
	RegisterTime         string   `protobuf:"bytes,5,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	HeartbeatTime        string   `protobuf:"bytes,6,opt,name=heartbeat_time,json=heartbeatTime,proto3" json:"heartbeat_time,omitempty"`
	UnRegisterTime       string   `protobuf:"bytes,7,opt,name=unRegister_time,json=unRegisterTime,proto3" json:"unRegister_time,omitempty"`
	DeviceInfo           string   `protobuf:"bytes,8,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectInfo) Reset()         { *m = ConnectInfo{} }
func (m *ConnectInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectInfo) ProtoMessage()    {}
func (*ConnectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{8}
}

func (m *ConnectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectInfo.Unmarshal(m, b)
}
func (m *ConnectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectInfo.Marshal(b, m, deterministic)
}
func (m *ConnectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectInfo.Merge(m, src)
}
func (m *ConnectInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectInfo.Size(m)
}
func (m *ConnectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectInfo proto.InternalMessageInfo

func (m *ConnectInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ConnectInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ConnectInfo) GetServerIp() string {
	if m != nil {
		return m.ServerIp
	}
	return ""
}

func (m *ConnectInfo) GetConnectIp() string {
	if m != nil {
		return m.ConnectIp
	}
	return ""
}

func (m *ConnectInfo) GetRegisterTime() string {
	if m != nil {
		return m.RegisterTime
	}
	return ""
}

func (m *ConnectInfo) GetHeartbeatTime() string {
	if m != nil {
		return m.HeartbeatTime
	}
	return ""
}

func (m *ConnectInfo) GetUnRegisterTime() string {
	if m != nil {
		return m.UnRegisterTime
	}
	return ""
}

func (m *ConnectInfo) GetDeviceInfo() string {
	if m != nil {
		return m.DeviceInfo
	}
	return ""
}

type OffConnectReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffConnectReq) Reset()         { *m = OffConnectReq{} }
func (m *OffConnectReq) String() string { return proto.CompactTextString(m) }
func (*OffConnectReq) ProtoMessage()    {}
func (*OffConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{9}
}

func (m *OffConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffConnectReq.Unmarshal(m, b)
}
func (m *OffConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffConnectReq.Marshal(b, m, deterministic)
}
func (m *OffConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffConnectReq.Merge(m, src)
}
func (m *OffConnectReq) XXX_Size() int {
	return xxx_messageInfo_OffConnectReq.Size(m)
}
func (m *OffConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OffConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_OffConnectReq proto.InternalMessageInfo

func (m *OffConnectReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OffConnectReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type GetUserConnectListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserConnectListReq) Reset()         { *m = GetUserConnectListReq{} }
func (m *GetUserConnectListReq) String() string { return proto.CompactTextString(m) }
func (*GetUserConnectListReq) ProtoMessage()    {}
func (*GetUserConnectListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{10}
}

func (m *GetUserConnectListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserConnectListReq.Unmarshal(m, b)
}
func (m *GetUserConnectListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserConnectListReq.Marshal(b, m, deterministic)
}
func (m *GetUserConnectListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserConnectListReq.Merge(m, src)
}
func (m *GetUserConnectListReq) XXX_Size() int {
	return xxx_messageInfo_GetUserConnectListReq.Size(m)
}
func (m *GetUserConnectListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserConnectListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserConnectListReq proto.InternalMessageInfo

func (m *GetUserConnectListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserConnectListReq) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetUserConnectListReq) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UserConnectListResp struct {
	UserConnectList      []*ConnectInfo `protobuf:"bytes,1,rep,name=user_connect_list,json=userConnectList,proto3" json:"user_connect_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserConnectListResp) Reset()         { *m = UserConnectListResp{} }
func (m *UserConnectListResp) String() string { return proto.CompactTextString(m) }
func (*UserConnectListResp) ProtoMessage()    {}
func (*UserConnectListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{11}
}

func (m *UserConnectListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserConnectListResp.Unmarshal(m, b)
}
func (m *UserConnectListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserConnectListResp.Marshal(b, m, deterministic)
}
func (m *UserConnectListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserConnectListResp.Merge(m, src)
}
func (m *UserConnectListResp) XXX_Size() int {
	return xxx_messageInfo_UserConnectListResp.Size(m)
}
func (m *UserConnectListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserConnectListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserConnectListResp proto.InternalMessageInfo

func (m *UserConnectListResp) GetUserConnectList() []*ConnectInfo {
	if m != nil {
		return m.UserConnectList
	}
	return nil
}

type ServerInfoReq struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	IsLocal              bool     `protobuf:"varint,2,opt,name=isLocal,proto3" json:"isLocal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfoReq) Reset()         { *m = ServerInfoReq{} }
func (m *ServerInfoReq) String() string { return proto.CompactTextString(m) }
func (*ServerInfoReq) ProtoMessage()    {}
func (*ServerInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{12}
}

func (m *ServerInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoReq.Unmarshal(m, b)
}
func (m *ServerInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoReq.Marshal(b, m, deterministic)
}
func (m *ServerInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoReq.Merge(m, src)
}
func (m *ServerInfoReq) XXX_Size() int {
	return xxx_messageInfo_ServerInfoReq.Size(m)
}
func (m *ServerInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoReq proto.InternalMessageInfo

func (m *ServerInfoReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ServerInfoReq) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

type BusinessInfo struct {
	ConnectLen           int64    `protobuf:"varint,1,opt,name=connect_len,json=connectLen,proto3" json:"connect_len,omitempty"`
	UserLen              int64    `protobuf:"varint,2,opt,name=user_len,json=userLen,proto3" json:"user_len,omitempty"`
	PendRegisterLen      int64    `protobuf:"varint,3,opt,name=pendRegister_len,json=pendRegisterLen,proto3" json:"pendRegister_len,omitempty"`
	PendUnregisterLen    int64    `protobuf:"varint,4,opt,name=pendUnregister_len,json=pendUnregisterLen,proto3" json:"pendUnregister_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessInfo) Reset()         { *m = BusinessInfo{} }
func (m *BusinessInfo) String() string { return proto.CompactTextString(m) }
func (*BusinessInfo) ProtoMessage()    {}
func (*BusinessInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{13}
}

func (m *BusinessInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessInfo.Unmarshal(m, b)
}
func (m *BusinessInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessInfo.Marshal(b, m, deterministic)
}
func (m *BusinessInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessInfo.Merge(m, src)
}
func (m *BusinessInfo) XXX_Size() int {
	return xxx_messageInfo_BusinessInfo.Size(m)
}
func (m *BusinessInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessInfo proto.InternalMessageInfo

func (m *BusinessInfo) GetConnectLen() int64 {
	if m != nil {
		return m.ConnectLen
	}
	return 0
}

func (m *BusinessInfo) GetUserLen() int64 {
	if m != nil {
		return m.UserLen
	}
	return 0
}

func (m *BusinessInfo) GetPendRegisterLen() int64 {
	if m != nil {
		return m.PendRegisterLen
	}
	return 0
}

func (m *BusinessInfo) GetPendUnregisterLen() int64 {
	if m != nil {
		return m.PendUnregisterLen
	}
	return 0
}

type SysInfo struct {
	Num_CPU              string   `protobuf:"bytes,1,opt,name=num_CPU,json=numCPU,proto3" json:"num_CPU,omitempty"`
	Num_CPU_USAGE        string   `protobuf:"bytes,2,opt,name=num_CPU_USAGE,json=numCPUUSAGE,proto3" json:"num_CPU_USAGE,omitempty"`
	Num_RAM              string   `protobuf:"bytes,3,opt,name=num_RAM,json=numRAM,proto3" json:"num_RAM,omitempty"`
	Num_RAM_USAGE        string   `protobuf:"bytes,4,opt,name=num_RAM_USAGE,json=numRAMUSAGE,proto3" json:"num_RAM_USAGE,omitempty"`
	Num_DISK             string   `protobuf:"bytes,5,opt,name=num_DISK,json=numDISK,proto3" json:"num_DISK,omitempty"`
	Num_DISK_USAGE       string   `protobuf:"bytes,6,opt,name=num_DISK_USAGE,json=numDISKUSAGE,proto3" json:"num_DISK_USAGE,omitempty"`
	Num_NETWORK          string   `protobuf:"bytes,7,opt,name=num_NETWORK,json=numNETWORK,proto3" json:"num_NETWORK,omitempty"`
	Num_NETWORK_USAGE    string   `protobuf:"bytes,8,opt,name=num_NETWORK_USAGE,json=numNETWORKUSAGE,proto3" json:"num_NETWORK_USAGE,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysInfo) Reset()         { *m = SysInfo{} }
func (m *SysInfo) String() string { return proto.CompactTextString(m) }
func (*SysInfo) ProtoMessage()    {}
func (*SysInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{14}
}

func (m *SysInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysInfo.Unmarshal(m, b)
}
func (m *SysInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysInfo.Marshal(b, m, deterministic)
}
func (m *SysInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysInfo.Merge(m, src)
}
func (m *SysInfo) XXX_Size() int {
	return xxx_messageInfo_SysInfo.Size(m)
}
func (m *SysInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SysInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SysInfo proto.InternalMessageInfo

func (m *SysInfo) GetNum_CPU() string {
	if m != nil {
		return m.Num_CPU
	}
	return ""
}

func (m *SysInfo) GetNum_CPU_USAGE() string {
	if m != nil {
		return m.Num_CPU_USAGE
	}
	return ""
}

func (m *SysInfo) GetNum_RAM() string {
	if m != nil {
		return m.Num_RAM
	}
	return ""
}

func (m *SysInfo) GetNum_RAM_USAGE() string {
	if m != nil {
		return m.Num_RAM_USAGE
	}
	return ""
}

func (m *SysInfo) GetNum_DISK() string {
	if m != nil {
		return m.Num_DISK
	}
	return ""
}

func (m *SysInfo) GetNum_DISK_USAGE() string {
	if m != nil {
		return m.Num_DISK_USAGE
	}
	return ""
}

func (m *SysInfo) GetNum_NETWORK() string {
	if m != nil {
		return m.Num_NETWORK
	}
	return ""
}

func (m *SysInfo) GetNum_NETWORK_USAGE() string {
	if m != nil {
		return m.Num_NETWORK_USAGE
	}
	return ""
}

type ServerInfo struct {
	NumGoroutine         string   `protobuf:"bytes,1,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	AllocMemory          string   `protobuf:"bytes,2,opt,name=alloc_memory,json=allocMemory,proto3" json:"alloc_memory,omitempty"`
	TotalAllocMemory     string   `protobuf:"bytes,3,opt,name=totalAlloc_memory,json=totalAllocMemory,proto3" json:"totalAlloc_memory,omitempty"`
	SysMemory            string   `protobuf:"bytes,4,opt,name=sys_memory,json=sysMemory,proto3" json:"sys_memory,omitempty"`
	Num_GC               string   `protobuf:"bytes,5,opt,name=num_GC,json=numGC,proto3" json:"num_GC,omitempty"`
	CPU                  string   `protobuf:"bytes,6,opt,name=CPU,proto3" json:"CPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{15}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetNumGoroutine() string {
	if m != nil {
		return m.NumGoroutine
	}
	return ""
}

func (m *ServerInfo) GetAllocMemory() string {
	if m != nil {
		return m.AllocMemory
	}
	return ""
}

func (m *ServerInfo) GetTotalAllocMemory() string {
	if m != nil {
		return m.TotalAllocMemory
	}
	return ""
}

func (m *ServerInfo) GetSysMemory() string {
	if m != nil {
		return m.SysMemory
	}
	return ""
}

func (m *ServerInfo) GetNum_GC() string {
	if m != nil {
		return m.Num_GC
	}
	return ""
}

func (m *ServerInfo) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

type Server struct {
	ServerId             string        `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerInfo           *ServerInfo   `protobuf:"bytes,2,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	BusinessInfo         *BusinessInfo `protobuf:"bytes,3,opt,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"`
	SysInfo              *SysInfo      `protobuf:"bytes,4,opt,name=sys_info,json=sysInfo,proto3" json:"sys_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{16}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *Server) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

func (m *Server) GetBusinessInfo() *BusinessInfo {
	if m != nil {
		return m.BusinessInfo
	}
	return nil
}

func (m *Server) GetSysInfo() *SysInfo {
	if m != nil {
		return m.SysInfo
	}
	return nil
}

type ServerInfoResp struct {
	Server               []*Server `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServerInfoResp) Reset()         { *m = ServerInfoResp{} }
func (m *ServerInfoResp) String() string { return proto.CompactTextString(m) }
func (*ServerInfoResp) ProtoMessage()    {}
func (*ServerInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{17}
}

func (m *ServerInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoResp.Unmarshal(m, b)
}
func (m *ServerInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoResp.Marshal(b, m, deterministic)
}
func (m *ServerInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoResp.Merge(m, src)
}
func (m *ServerInfoResp) XXX_Size() int {
	return xxx_messageInfo_ServerInfoResp.Size(m)
}
func (m *ServerInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoResp proto.InternalMessageInfo

func (m *ServerInfoResp) GetServer() []*Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func init() {
	proto.RegisterType((*NullResp)(nil), "connect.NullResp")
	proto.RegisterType((*NullReq)(nil), "connect.NullReq")
	proto.RegisterType((*GetsQueryItem)(nil), "connect.GetsQueryItem")
	proto.RegisterType((*GetsReq)(nil), "connect.GetsReq")
	proto.RegisterType((*SendOneMsgReq)(nil), "connect.SendOneMsgReq")
	proto.RegisterType((*At)(nil), "connect.At")
	proto.RegisterType((*SendManyMsgReq)(nil), "connect.SendManyMsgReq")
	proto.RegisterType((*GetConnectInfoReq)(nil), "connect.GetConnectInfoReq")
	proto.RegisterType((*ConnectInfo)(nil), "connect.ConnectInfo")
	proto.RegisterType((*OffConnectReq)(nil), "connect.OffConnectReq")
	proto.RegisterType((*GetUserConnectListReq)(nil), "connect.GetUserConnectListReq")
	proto.RegisterType((*UserConnectListResp)(nil), "connect.UserConnectListResp")
	proto.RegisterType((*ServerInfoReq)(nil), "connect.ServerInfoReq")
	proto.RegisterType((*BusinessInfo)(nil), "connect.BusinessInfo")
	proto.RegisterType((*SysInfo)(nil), "connect.SysInfo")
	proto.RegisterType((*ServerInfo)(nil), "connect.ServerInfo")
	proto.RegisterType((*Server)(nil), "connect.Server")
	proto.RegisterType((*ServerInfoResp)(nil), "connect.ServerInfoResp")
}

func init() { proto.RegisterFile("conn.proto", fileDescriptor_f401a58c1fc7ceef) }

var fileDescriptor_f401a58c1fc7ceef = []byte{
	// 1199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4b, 0x73, 0xdb, 0x54,
	0x14, 0x1e, 0x3f, 0xe2, 0xc7, 0x71, 0xec, 0xd8, 0xb7, 0x6d, 0xea, 0xba, 0xb4, 0x09, 0x02, 0xa6,
	0x81, 0x96, 0x2c, 0x02, 0x33, 0x9d, 0xb2, 0x60, 0xea, 0xb8, 0xc1, 0x78, 0x12, 0x27, 0x41, 0x4e,
	0xda, 0x1d, 0x1e, 0xc5, 0xba, 0x36, 0x1a, 0xa4, 0x2b, 0x45, 0xf7, 0xaa, 0x83, 0xf9, 0x15, 0xb0,
	0x60, 0xc5, 0x96, 0x9f, 0xc2, 0x86, 0x5f, 0xc0, 0x0c, 0xbf, 0x86, 0x39, 0xf7, 0x21, 0xc9, 0x8d,
	0x27, 0x8b, 0x6e, 0xba, 0xd3, 0xfd, 0xce, 0x43, 0xdf, 0x3d, 0xaf, 0x7b, 0x00, 0x66, 0x21, 0x63,
	0xfb, 0x51, 0x1c, 0x8a, 0x90, 0x54, 0xf1, 0x9b, 0xce, 0x84, 0x05, 0x50, 0x3b, 0x4d, 0x7c, 0xdf,
	0xa6, 0x3c, 0xb2, 0xea, 0x50, 0x55, 0xdf, 0xd7, 0xd6, 0xcf, 0xd0, 0x1c, 0x52, 0xc1, 0x7f, 0x48,
	0x68, 0xbc, 0x1c, 0x09, 0x1a, 0x90, 0x36, 0x94, 0x8e, 0xe9, 0xb2, 0x5b, 0xd8, 0x2d, 0xec, 0xd5,
	0x6d, 0xfc, 0x44, 0xe4, 0xb5, 0xe3, 0x77, 0x8b, 0x0a, 0x79, 0xed, 0xf8, 0x64, 0x1b, 0x2a, 0xdf,
	0x3b, 0xcc, 0xf5, 0x69, 0xb7, 0x24, 0x41, 0x7d, 0x22, 0x8f, 0x01, 0x4e, 0xe9, 0x2f, 0x42, 0xcb,
	0xca, 0x52, 0x96, 0x43, 0xac, 0x3f, 0x0b, 0x50, 0xc5, 0xbf, 0xd9, 0xf4, 0x9a, 0x3c, 0x83, 0x0d,
	0xf9, 0xd3, 0x6e, 0x61, 0xb7, 0xb4, 0xd7, 0x38, 0xd8, 0xde, 0xd7, 0x44, 0xf7, 0x57, 0xe8, 0xd8,
	0x4a, 0x89, 0x74, 0xa1, 0x7a, 0x16, 0xbb, 0x34, 0x3e, 0x5c, 0x6a, 0x1e, 0xe6, 0x48, 0x08, 0x94,
	0x27, 0x61, 0x2c, 0x34, 0x13, 0xf9, 0x8d, 0xda, 0x83, 0x24, 0x8e, 0x29, 0x13, 0x92, 0x44, 0xc9,
	0x36, 0x47, 0xd2, 0x83, 0xda, 0xb9, 0xb3, 0xa0, 0x13, 0xef, 0x57, 0xda, 0xdd, 0x90, 0xa2, 0xf4,
	0x6c, 0xfd, 0x5b, 0x84, 0xe6, 0x84, 0x32, 0xf7, 0x8c, 0xd1, 0x31, 0x5f, 0x20, 0xc7, 0x1d, 0x68,
	0x70, 0xca, 0x5c, 0x1a, 0x4f, 0xc5, 0x32, 0xa2, 0x3a, 0x26, 0xa0, 0xa0, 0x8b, 0x65, 0x44, 0xc9,
	0x43, 0xa8, 0x6b, 0x05, 0xcf, 0xd5, 0xc4, 0x6a, 0x0a, 0x18, 0xb9, 0x64, 0x0f, 0xda, 0x5a, 0xe8,
	0xd2, 0xb7, 0xde, 0x8c, 0xa2, 0x8e, 0x62, 0xd9, 0x52, 0xf8, 0x2b, 0x09, 0x8f, 0x5c, 0xfc, 0x4f,
	0x4c, 0x67, 0xd4, 0x7b, 0xab, 0x1c, 0xe9, 0xc0, 0x19, 0x68, 0xe4, 0x92, 0x67, 0x40, 0x52, 0x85,
	0xcc, 0xd9, 0x86, 0xd4, 0x6b, 0x1b, 0x49, 0xea, 0xee, 0x21, 0xd4, 0x23, 0x07, 0xaf, 0x8b, 0x4a,
	0x15, 0xc5, 0x4a, 0x01, 0x4a, 0x88, 0x7f, 0x9f, 0x0a, 0x2f, 0xa0, 0xdd, 0x6a, 0x46, 0xf9, 0xc2,
	0x0b, 0x28, 0x79, 0x00, 0xb5, 0x80, 0x2f, 0xd4, 0x6d, 0x6b, 0x2a, 0xce, 0x01, 0x5f, 0xc8, 0xab,
	0xee, 0x40, 0x03, 0x45, 0xb3, 0x90, 0x09, 0x8c, 0x6b, 0x5d, 0x71, 0x0c, 0xf8, 0x62, 0xa0, 0x10,
	0xb4, 0xf5, 0xf8, 0xd4, 0x0f, 0x67, 0x8e, 0xdf, 0x85, 0xdd, 0xc2, 0x5e, 0xcd, 0xae, 0x7a, 0xfc,
	0x04, 0x8f, 0xd6, 0xb7, 0x50, 0xec, 0x1b, 0x05, 0x47, 0xf4, 0x7d, 0x5f, 0x86, 0x52, 0x2a, 0xf4,
	0xf1, 0x48, 0x1e, 0x01, 0x38, 0x62, 0x9a, 0x70, 0xbc, 0x2c, 0xef, 0x16, 0x77, 0x4b, 0x7b, 0x75,
	0xbb, 0xee, 0x88, 0x4b, 0x05, 0x58, 0xff, 0x15, 0xa1, 0x85, 0x99, 0x19, 0x3b, 0x6c, 0xf9, 0xa1,
	0x53, 0x53, 0xfa, 0x40, 0xa9, 0x79, 0x08, 0x45, 0x47, 0xc8, 0xa4, 0x34, 0x0e, 0x1a, 0x69, 0xb3,
	0xf4, 0x85, 0x5d, 0x74, 0xc4, 0x4a, 0xde, 0xea, 0xb7, 0xe6, 0x0d, 0xde, 0xcd, 0x9b, 0x35, 0x82,
	0xce, 0x90, 0x8a, 0x81, 0x72, 0x38, 0x62, 0xf3, 0x10, 0xc3, 0x7b, 0x1f, 0xaa, 0x98, 0x0d, 0x64,
	0xa9, 0x42, 0x5b, 0x51, 0xc9, 0x41, 0x8e, 0xd9, 0x2d, 0x75, 0x58, 0x5d, 0x7d, 0x3b, 0xeb, 0x8f,
	0x22, 0x34, 0x72, 0x8e, 0xde, 0xcf, 0x8b, 0x0a, 0x43, 0x2c, 0x03, 0x1e, 0xe9, 0xac, 0xd4, 0x14,
	0x30, 0x8a, 0xb0, 0x52, 0xf4, 0xdd, 0x51, 0xaa, 0x3a, 0xa5, 0xae, 0x91, 0x51, 0x44, 0x3e, 0x81,
	0x66, 0x4c, 0x17, 0x1e, 0x17, 0x58, 0x18, 0x18, 0x46, 0x95, 0x88, 0x4d, 0x03, 0xca, 0x50, 0x7e,
	0x06, 0xad, 0x9f, 0xa8, 0x13, 0x8b, 0x2b, 0xea, 0x08, 0xa5, 0xa5, 0x32, 0xd1, 0x4c, 0x51, 0xa9,
	0xf6, 0x04, 0xb6, 0x12, 0x66, 0xaf, 0x78, 0x53, 0x49, 0x69, 0x65, 0xb0, 0x54, 0xdc, 0x81, 0x86,
	0xb9, 0x0d, 0x9b, 0x87, 0xba, 0x71, 0x40, 0xdf, 0x87, 0xcd, 0x43, 0xeb, 0x08, 0x9a, 0x67, 0xf3,
	0xb9, 0x8e, 0xcc, 0xfb, 0x87, 0xf7, 0x47, 0xb8, 0x37, 0xa4, 0xb2, 0x29, 0xb4, 0xab, 0x13, 0x8f,
	0xdf, 0xee, 0x6e, 0x1b, 0x2a, 0xe1, 0x7c, 0xce, 0xa9, 0x90, 0xbe, 0xca, 0xb6, 0x3e, 0x91, 0xbb,
	0xb0, 0xe1, 0x7b, 0x81, 0xa7, 0xa6, 0x66, 0xd9, 0x56, 0x07, 0xeb, 0x0d, 0xdc, 0xb9, 0xe1, 0x9c,
	0x47, 0xe4, 0x25, 0x74, 0xa4, 0x77, 0x13, 0x77, 0xdf, 0xe3, 0x42, 0x4f, 0xed, 0xbb, 0x69, 0x21,
	0xe6, 0xeb, 0x67, 0x2b, 0x59, 0xf5, 0x62, 0x7d, 0x87, 0x83, 0x55, 0x26, 0x50, 0x97, 0x57, 0x2e,
	0xc5, 0x86, 0xb2, 0x49, 0xb1, 0x8b, 0xd3, 0x5b, 0x0f, 0x0e, 0xc9, 0x3a, 0x37, 0x47, 0xfe, 0x2a,
	0xc0, 0xe6, 0x61, 0xc2, 0x3d, 0x46, 0x39, 0x97, 0x05, 0xb6, 0x03, 0x8d, 0x94, 0x15, 0x65, 0xd2,
	0x53, 0xc9, 0x36, 0x05, 0x72, 0x42, 0x19, 0x36, 0x86, 0xe4, 0x8e, 0xd2, 0xa2, 0x7a, 0x0a, 0xf0,
	0x8c, 0xa2, 0xcf, 0xa1, 0x1d, 0x51, 0xe6, 0xa6, 0x09, 0x46, 0x95, 0x92, 0x54, 0xd9, 0xca, 0xe3,
	0xa8, 0xfa, 0x25, 0x10, 0x84, 0x2e, 0x59, 0x9c, 0x57, 0x56, 0x4f, 0x4b, 0x67, 0x55, 0x72, 0x42,
	0x99, 0xf5, 0x7b, 0x11, 0xaa, 0x93, 0x25, 0x37, 0x2d, 0xc0, 0x92, 0x60, 0x3a, 0x38, 0xbf, 0x34,
	0xa9, 0x61, 0x49, 0x30, 0x38, 0xbf, 0x24, 0x16, 0x34, 0xb5, 0x60, 0x7a, 0x39, 0xe9, 0x0f, 0x8f,
	0x74, 0xb6, 0x1b, 0x4a, 0x2c, 0x21, 0x63, 0x6c, 0xf7, 0xc7, 0xe6, 0xa1, 0x65, 0x49, 0x60, 0xf7,
	0xc7, 0xc6, 0xd8, 0xee, 0x8f, 0xb5, 0x71, 0x39, 0x35, 0xb6, 0xfb, 0x63, 0x65, 0xfc, 0x00, 0x6a,
	0xa8, 0xf3, 0x6a, 0x34, 0x39, 0xd6, 0x5d, 0x80, 0xce, 0xf0, 0x48, 0x3e, 0x85, 0x96, 0x11, 0x69,
	0x7b, 0xd5, 0x00, 0x9b, 0x5a, 0x41, 0x39, 0xd8, 0x01, 0xf4, 0x37, 0x3d, 0x3d, 0xba, 0x78, 0x73,
	0x66, 0x1f, 0xeb, 0xda, 0x07, 0x96, 0x04, 0x1a, 0x21, 0x5f, 0x40, 0x27, 0xa7, 0xa0, 0x3d, 0xa9,
	0xea, 0xdf, 0xca, 0xd4, 0x24, 0x6c, 0xfd, 0x53, 0x00, 0xc8, 0x6a, 0x00, 0xfb, 0x14, 0x4d, 0x17,
	0x61, 0x1c, 0x26, 0xc2, 0x63, 0x66, 0x80, 0x23, 0x81, 0xa1, 0xc1, 0xc8, 0xc7, 0xb0, 0xe9, 0xf8,
	0x7e, 0x38, 0x9b, 0x06, 0x34, 0x08, 0x63, 0xf3, 0xf2, 0x37, 0x24, 0x36, 0x96, 0x10, 0x79, 0x0a,
	0x1d, 0x11, 0x0a, 0xc7, 0xef, 0xe7, 0xf5, 0x54, 0xac, 0xda, 0x99, 0x40, 0x2b, 0x3f, 0x02, 0xe0,
	0x4b, 0x6e, 0xb4, 0xf4, 0xec, 0xe0, 0x4b, 0xae, 0xc5, 0xf7, 0x00, 0xc3, 0x3b, 0x1d, 0x0e, 0x74,
	0xb8, 0x36, 0x90, 0xcc, 0x00, 0xd7, 0x1f, 0xcc, 0x9e, 0x8a, 0x10, 0x7e, 0x5a, 0x7f, 0x17, 0xa0,
	0xa2, 0xee, 0x72, 0x7b, 0x21, 0x7f, 0x8d, 0x6f, 0x94, 0x12, 0xe2, 0x5c, 0x28, 0xca, 0xd9, 0x7d,
	0x27, 0x6d, 0x99, 0x5c, 0x4b, 0x00, 0xcf, 0x42, 0xf3, 0x0d, 0x34, 0xaf, 0x74, 0x8d, 0x2b, 0xbb,
	0x92, 0xb4, 0xbb, 0x97, 0xda, 0xe5, 0x3b, 0xc0, 0xde, 0xbc, 0xca, 0xf7, 0xc3, 0x53, 0xa8, 0xe1,
	0x0d, 0xa5, 0x59, 0x59, 0x9a, 0xb5, 0xb3, 0xdf, 0xa9, 0x8a, 0xb4, 0xab, 0x5c, 0x7d, 0x58, 0x2f,
	0xf0, 0x51, 0xcd, 0xba, 0x92, 0x47, 0xe4, 0x09, 0x54, 0x14, 0x11, 0xdd, 0xde, 0x5b, 0xef, 0x70,
	0xb5, 0xb5, 0xf8, 0xe0, 0xb7, 0x12, 0x54, 0x75, 0x83, 0x93, 0x43, 0x68, 0x2d, 0x56, 0xde, 0x0f,
	0xd2, 0xcb, 0xef, 0x72, 0xab, 0x0f, 0x4b, 0x6f, 0xed, 0xc4, 0x20, 0xcf, 0x01, 0xc2, 0x74, 0x40,
	0x92, 0x6c, 0x17, 0x5c, 0x99, 0x9a, 0xbd, 0x4e, 0x8a, 0x9b, 0x4d, 0x96, 0xd8, 0x40, 0x16, 0x37,
	0x46, 0x22, 0x79, 0x9c, 0x27, 0x70, 0x73, 0x5e, 0xf6, 0x3e, 0x4a, 0xe5, 0xeb, 0xe6, 0xdd, 0x73,
	0x90, 0x7b, 0x84, 0x5a, 0x03, 0x73, 0x64, 0x56, 0x76, 0xc3, 0x75, 0x64, 0x5e, 0xa8, 0x9d, 0x44,
	0x6f, 0x29, 0xe4, 0xfe, 0x8a, 0x65, 0xb6, 0xbb, 0xac, 0x33, 0x7d, 0x09, 0xcd, 0x05, 0x15, 0xb9,
	0x06, 0xd9, 0x5e, 0x57, 0x26, 0xf4, 0xba, 0x77, 0x7f, 0x2d, 0xce, 0xa3, 0xab, 0x8a, 0xdc, 0xf7,
	0xbf, 0xfa, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x83, 0x21, 0xd4, 0x95, 0xfd, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectClient is the client API for Connect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectClient interface {
	//  rpc getConnectList(GetConnectListReq) returns(NullResp); // 获取连接列表
	GetConnectInfo(ctx context.Context, in *GetConnectInfoReq, opts ...grpc.CallOption) (*ConnectInfo, error)
	OffConnect(ctx context.Context, in *OffConnectReq, opts ...grpc.CallOption) (*NullResp, error)
	GetUserConnectList(ctx context.Context, in *GetUserConnectListReq, opts ...grpc.CallOption) (*UserConnectListResp, error)
	SendOneMsg(ctx context.Context, in *SendOneMsgReq, opts ...grpc.CallOption) (*NullResp, error)
	SendManyMsg(ctx context.Context, in *SendManyMsgReq, opts ...grpc.CallOption) (*NullResp, error)
	GetServerInfo(ctx context.Context, in *ServerInfoReq, opts ...grpc.CallOption) (*ServerInfoResp, error)
}

type connectClient struct {
	cc *grpc.ClientConn
}

func NewConnectClient(cc *grpc.ClientConn) ConnectClient {
	return &connectClient{cc}
}

func (c *connectClient) GetConnectInfo(ctx context.Context, in *GetConnectInfoReq, opts ...grpc.CallOption) (*ConnectInfo, error) {
	out := new(ConnectInfo)
	err := c.cc.Invoke(ctx, "/connect.Connect/getConnectInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) OffConnect(ctx context.Context, in *OffConnectReq, opts ...grpc.CallOption) (*NullResp, error) {
	out := new(NullResp)
	err := c.cc.Invoke(ctx, "/connect.Connect/offConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) GetUserConnectList(ctx context.Context, in *GetUserConnectListReq, opts ...grpc.CallOption) (*UserConnectListResp, error) {
	out := new(UserConnectListResp)
	err := c.cc.Invoke(ctx, "/connect.Connect/getUserConnectList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) SendOneMsg(ctx context.Context, in *SendOneMsgReq, opts ...grpc.CallOption) (*NullResp, error) {
	out := new(NullResp)
	err := c.cc.Invoke(ctx, "/connect.Connect/sendOneMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) SendManyMsg(ctx context.Context, in *SendManyMsgReq, opts ...grpc.CallOption) (*NullResp, error) {
	out := new(NullResp)
	err := c.cc.Invoke(ctx, "/connect.Connect/sendManyMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectClient) GetServerInfo(ctx context.Context, in *ServerInfoReq, opts ...grpc.CallOption) (*ServerInfoResp, error) {
	out := new(ServerInfoResp)
	err := c.cc.Invoke(ctx, "/connect.Connect/getServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectServer is the server API for Connect service.
type ConnectServer interface {
	//  rpc getConnectList(GetConnectListReq) returns(NullResp); // 获取连接列表
	GetConnectInfo(context.Context, *GetConnectInfoReq) (*ConnectInfo, error)
	OffConnect(context.Context, *OffConnectReq) (*NullResp, error)
	GetUserConnectList(context.Context, *GetUserConnectListReq) (*UserConnectListResp, error)
	SendOneMsg(context.Context, *SendOneMsgReq) (*NullResp, error)
	SendManyMsg(context.Context, *SendManyMsgReq) (*NullResp, error)
	GetServerInfo(context.Context, *ServerInfoReq) (*ServerInfoResp, error)
}

// UnimplementedConnectServer can be embedded to have forward compatible implementations.
type UnimplementedConnectServer struct {
}

func (*UnimplementedConnectServer) GetConnectInfo(ctx context.Context, req *GetConnectInfoReq) (*ConnectInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectInfo not implemented")
}
func (*UnimplementedConnectServer) OffConnect(ctx context.Context, req *OffConnectReq) (*NullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OffConnect not implemented")
}
func (*UnimplementedConnectServer) GetUserConnectList(ctx context.Context, req *GetUserConnectListReq) (*UserConnectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserConnectList not implemented")
}
func (*UnimplementedConnectServer) SendOneMsg(ctx context.Context, req *SendOneMsgReq) (*NullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOneMsg not implemented")
}
func (*UnimplementedConnectServer) SendManyMsg(ctx context.Context, req *SendManyMsgReq) (*NullResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendManyMsg not implemented")
}
func (*UnimplementedConnectServer) GetServerInfo(ctx context.Context, req *ServerInfoReq) (*ServerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}

func RegisterConnectServer(s *grpc.Server, srv ConnectServer) {
	s.RegisterService(&_Connect_serviceDesc, srv)
}

func _Connect_GetConnectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).GetConnectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/GetConnectInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).GetConnectInfo(ctx, req.(*GetConnectInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_OffConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).OffConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/OffConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).OffConnect(ctx, req.(*OffConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_GetUserConnectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConnectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).GetUserConnectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/GetUserConnectList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).GetUserConnectList(ctx, req.(*GetUserConnectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_SendOneMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOneMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).SendOneMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/SendOneMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).SendOneMsg(ctx, req.(*SendOneMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_SendManyMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendManyMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).SendManyMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/SendManyMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).SendManyMsg(ctx, req.(*SendManyMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connect_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connect.Connect/GetServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectServer).GetServerInfo(ctx, req.(*ServerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connect.Connect",
	HandlerType: (*ConnectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getConnectInfo",
			Handler:    _Connect_GetConnectInfo_Handler,
		},
		{
			MethodName: "offConnect",
			Handler:    _Connect_OffConnect_Handler,
		},
		{
			MethodName: "getUserConnectList",
			Handler:    _Connect_GetUserConnectList_Handler,
		},
		{
			MethodName: "sendOneMsg",
			Handler:    _Connect_SendOneMsg_Handler,
		},
		{
			MethodName: "sendManyMsg",
			Handler:    _Connect_SendManyMsg_Handler,
		},
		{
			MethodName: "getServerInfo",
			Handler:    _Connect_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conn.proto",
}
